import{a as S,S as q,i as l}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const E="50254801-91971d45cfc13d9e951cbfc82",P="https://pixabay.com/api/";async function y(i,t=1){const o={key:E,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await S.get(P,{params:o})).data}const p=document.querySelector(".loader"),h=document.querySelector(".gallery"),g=document.querySelector(".load-more");let c=null;function b(){p.classList.remove("visually-hidden")}function d(){p.classList.add("visually-hidden")}function B(){h.innerHTML=""}function $(){g.classList.remove("visually-hidden")}function u(){g.classList.add("visually-hidden")}function L(i){const t=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:a,comments:v,downloads:w})=>`<li class="gallery-item">
    <a href="${n}"><img src="${o}" alt="${e}" title=""/></a>
    <div class="cont">
      <p><b>Likes</b><br>${r}</p>
      <p><b>Views</b><br>${a}</p>
      <p><b>Comments</b><br>${v}</p>
      <p><b>Downloads</b><br>${w}</p>
    </div>
</li>`).join("");h.insertAdjacentHTML("beforeend",t),c?c.refresh():c=new q(".gallery a",{captionsData:"alt",captionDelay:250})}const m=document.querySelector("form"),R=document.querySelector(".load-more");let s=1,f="";m.addEventListener("submit",async i=>{i.preventDefault(),B(),u(),b();const t=i.currentTarget.elements["search-text"].value.trim();if(!t)return d(),l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});try{f=t,s=1;const o=await y(f,s);if(o.hits.length===0)return l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});L(o.hits),o.totalHits>s*15?$():u()}catch{l.error({title:"Error",message:"Sorry, something went wrong. Please try again!",position:"topRight"})}finally{d(),m.reset()}});R.addEventListener("click",async()=>{s+=1,b();try{const i=await y(f,s);L(i.hits),i.totalHits<=s*15&&(u(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const t=document.querySelector(".gallery").firstElementChild;if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch{l.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{d()}});
//# sourceMappingURL=index.js.map
