import{a as E,S as x,i as l}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const P="50254801-91971d45cfc13d9e951cbfc82",B="https://pixabay.com/api/";async function m(i,t=1){const o={key:P,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await E.get(B,{params:o})).data}const h=document.querySelector(".loader"),g=document.querySelector(".gallery"),p=document.querySelector(".load-more"),L=document.querySelector(".loading-text");let d=null;function $(){h.classList.remove("visually-hidden")}function f(){h.classList.add("visually-hidden")}function R(){g.innerHTML=""}function b(){p.classList.remove("visually-hidden")}function c(){p.classList.add("visually-hidden")}function T(){L.classList.remove("visually-hidden")}function v(){L.classList.add("visually-hidden")}function w(i){const t=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:a,comments:S,downloads:q})=>`<li class="gallery-item">
    <a href="${n}"><img src="${o}" alt="${e}" title=""/></a>
    <div class="cont">
      <p><b>Likes</b><br>${r}</p>
      <p><b>Views</b><br>${a}</p>
      <p><b>Comments</b><br>${S}</p>
      <p><b>Downloads</b><br>${q}</p>
    </div>
</li>`).join("");g.insertAdjacentHTML("beforeend",t),d?d.refresh():d=new x(".gallery a",{captionsData:"alt",captionDelay:250})}const y=document.querySelector("form"),O=document.querySelector(".load-more");let s=1,u="";y.addEventListener("submit",async i=>{i.preventDefault(),R(),c(),v(),$();const t=i.currentTarget.elements["search-text"].value.trim();if(!t)return f(),l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});try{u=t,s=1;const o=await m(u,s);if(o.hits.length===0)return l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});w(o.hits),o.totalHits>s*15?b():c()}catch{l.error({title:"Error",message:"Sorry, something went wrong. Please try again!",position:"topRight"})}finally{f(),y.reset()}});O.addEventListener("click",async()=>{s+=1,c(),T();try{const i=await m(u,s);w(i.hits),i.totalHits<=s*15?(c(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b();const t=document.querySelector(".gallery").firstElementChild;if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch{l.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{v()}});
//# sourceMappingURL=index.js.map
